#!/usr/bin/env python3

import argparse
import pathlib
import subprocess
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate the packaged CLI reference.")
    parser.add_argument("--binary", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args()


def listed_commands(help_text: str) -> list[str]:
    names = []
    in_commands = False
    for line in help_text.splitlines():
        stripped = line.strip()
        if stripped in ("Commands:", "Waveform commands:", "Helper commands:"):
            in_commands = True
            continue
        if in_commands and stripped == "Options:":
            break
        if in_commands and len(line) - len(line.lstrip()) == 2 and stripped:
            names.append(stripped.split()[0])
    return names


def append_command(binary: pathlib.Path, command: tuple[str, ...], sections: list[str]) -> None:
    invocation = [str(binary), *command, "--help"]
    result = subprocess.run(invocation, check=True, capture_output=True, text=True)
    help_text = "\n".join(line.rstrip() for line in result.stdout.splitlines())
    name = " ".join(("wavepeek", *command))
    sections.extend(("", f"## `{name}`", "", "```text", help_text, "```"))

    children = listed_commands(result.stdout)
    if command and children[-1:] == ["help"]:
        children.pop()
    for child in children:
        append_command(binary, (*command, child), sections)


def render(binary: pathlib.Path) -> str:
    sections = [
        "<!-- Generated by `just update-cli-reference`; do not edit. -->",
        "# CLI reference",
        "",
        "This page contains the detailed help from the version-matched `wavepeek` binary.",
    ]
    append_command(binary, (), sections)
    return "\n".join(sections) + "\n"


def main() -> int:
    args = parse_args()
    try:
        generated = render(args.binary)
    except (OSError, subprocess.CalledProcessError) as error:
        print(f"error: CLI reference generation failed: {error}", file=sys.stderr)
        return 1
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != generated:
            print(
                f"error: CLI reference is stale: run `just update-cli-reference` ({args.output})",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
