site_name: wavepeek
site_description: Deterministic RTL waveform inspection for scripts, CI, and agents.
site_url: https://kleverhq.github.io/wavepeek/
repo_url: https://github.com/kleverhq/wavepeek
repo_name: kleverhq/wavepeek
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
plugins:
  - search
extra:
  scope: /wavepeek/
extra_css:
  - monochrome.css
markdown_extensions:
  - admonition
  - toc:
      permalink: true
